name: constellations_list
description:
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared/

  cupertino_icons: ^1.0.6

dev_dependencies:


flutter:

  uses-material-design: true

  assets:
    - images/
    - packages/constellations_list/assets/glow.png

  fonts:
    - family: DMSerif
      fonts:
        - asset: fonts/DMSerifDisplay-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Playfair
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf