name: drink_rewards_list
description:
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared/

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700